 INSERT [dbo].[D00_TBGENERAL] ([codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'1', N'Tipo Documento', N'tpdoc01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ([codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'2', N'sexo', N'sex001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'3', N'grado instruccion', N'grd001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'4', N'Estado Civil', N'cvl001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'5', N'Ocupacion', N'ocu001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'6', N'Grupo Sangre', N'sang001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'7', N'Factor RH', N'fh001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'8', N'Parentesco', N'par001', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'9', N'Tipo Via', N'tpv01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'10', N'Etnico', N'etn01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'10', N'Etnico', N'etn01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'11', N'Religion', N'rel01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'12', N'Consultorio', N'consu01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'13', N'Tipo Empleado', N'emp01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'14', N'Tipo Paciente', N'tpac01', CAST(N'1900-01-01' AS Date), N'')
INSERT [dbo].[D00_TBGENERAL] ( [codTab], [descripcion], [tipo], [fechaCreate], [usuCreate]) VALUES (N'15', N'Especialidad', N'esp01', CAST(N'1900-01-01' AS Date), N'')

INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD001', N'LIBRETA ELECTORAL O DNI', N'L.E/ DNI', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD002', N'CARNET DE EXTRANJERIA', N'CARNET EXT', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD003', N'REGISTRO UNICO CONTRIBUYENTES', N'RUC', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD004', N'PASAPORTE', N'', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD005', N'PARTIDA NACIMIENTO -IDENTIDAD', N'', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPD006', N'OTROS', N'', N'www.sunat.gob.pe/pdt/pdtModulos/independientes/p695/TipoDoc.htm', N'          ', 1)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'SEX0001', N'MASCULINO', N'M', N'', N'          ', 2)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'SEX0002', N'FEMENINO', N'F', N'', N'          ', 2)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0001', N'SIN INSTRUCCIÓN', N'SI', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0002', N'INICIAL', N'I', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0001', N'PRIMARIA COMPLETA', N'PC', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0002', N'PRIMARIA INCOMPLETA', N'PI', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0001', N'SECUNDARIA COMPLETA', N'SC', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0002', N'SECUNDARIA INCOMPLETA', N'SI', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0001', N'SUPERIOR COMPLETO	', N'SUC', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'GRD0001', N'SUPERIOR INCOMPLETO', N'SUI', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 3)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC001', N'SOLTERA/O', N'S', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC002', N'CONVIVIENTE', N'CO', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC003', N'CASADA/O', N'C', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC004', N'SEPARADA/O', N'SP', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC005', N'DIVORCIADA/O', N'D', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC006', N'VIUDA/O', N'V', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EDC007', N'OTROS', N'O', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 4)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHO001', N'TRABAJADOR/A ESTABLE', N'S', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 5)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHO002', N'EVENTUAL', N'V', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 5)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHO003', N'SIN OCUPACION', N'SO', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 5)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHO004', N'JUBILADA/O', N'J', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 5)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHO005', N'ESTUDIANTE', N'E', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 5)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00001', N'AB POSITIVO', N'AB+', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00002', N'AB NEGATIVO', N'AB-', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00003', N'A POSITIVO', N'A+', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00004', N'A NEGATIVO', N'A-', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00005', N'B POSITIVO', N'B+', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00006', N'B NEGATIVO', N'B-', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00007', N'O POSITIVO', N'O+', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00008', N'O NEGATIVO', N'O-', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'G00009', N'NO REFIERE', N'', N'', N'          ', 6)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHC035', N'POSITIVO', N'+', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 7)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHC035', N'NEGATIVO', N'-', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 7)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP001', N'PADRE', N'P', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP002', N'MADRE', N'M', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP003', N'HIJO/A', N'H', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP004', N'ABUELA/O', N'A', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP005', N'TIA/O', N'T', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP006', N'NIETA/O', N'N', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP007', N'PADRASTRO', N'PA', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP008', N'MADRASTRA', N'MA', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP009', N'SOBRINA/O', N'S', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP010', N'PRIMA/O', N'PR', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP011', N'BIS-ABUELA/O', N'BA', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP012', N'AMIGA/O', N'AMG', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP013', N'HERMANA/O', N'HM', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP014', N'YERNO', N'Y', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'ANP015', N'NUERA', N'NA', N'NTS N° 139 MINSA/2018/DGAIN', N'          ', 8)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV001', N'ALAMEDA', N'AL', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV002', N'AVENIDA', N'AV', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV003', N'BAJADA', N'BA', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV004', N'BOULEVARD', N'BO', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV005', N'CALLE', N'CA', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV006', N'CALLEJON', N'CLL', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV07', N'CAMINO', N'CM', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV008', N'CARRETERA', N'CR', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV009', N'CUESTA', N'CU', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV010', N'GALERIA', N'GA', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV011', N'JIRON', N'JR', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV012', N'MALECON', N'ML', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV013', N'OVALO', N'OV', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV014', N'PASAJE', N'PJE', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV015', N'PARQUE', N'PQ', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV016', N'PASEO', N'PAS', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV017', N'PLAZA', N'PL', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV018', N'PLAZUELA', N'PZ', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV019', N'PROLONGACION', N'PRO', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV020', N'PUENTE', N'PU', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPV021', N'SENDERO', N'SE', N'', N'          ', 9)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DOE01', N'ASIATICO', N'', N'', N'          ', 10)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DOE02', N'NEGRO', N'', N'', N'          ', 10)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DOE03', N'HISPANO', N'', N'', N'          ', 10)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DOE04', N'BLANCO', N'', N'', N'          ', 10)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DOE05', N'OTROS', N'', N'', N'          ', 10)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR001', N'JUDAISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR002', N'ISLAMISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR003', N'CRISTIANISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR004', N'HINDUISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR005', N'BUDISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR006', N'RELIGION TRADICIONAL CHINA', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR007', N'ESPIRITISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR008', N'HELENISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR009', N'INDIGENAS', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR010', N'NEOPAGANISMO', N'', N'RM N° 329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR011', N'TAOISMO', N'', N'329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'DHR012', N'OTROS', N'', N'329, 2011/MINSA', N'          ', 11)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS01', N'CONSULTORIO1', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS02', N'CONSULTORIO2', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS03', N'CONSULTORIO3', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS04', N'CONSULTORIO4', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS05', N'CONSULTORIO5', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS06', N'CONSULTORIO6', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS07', N'CONSULTORIO7', N'', N'', N'          ', 13)
GO
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS08', N'CONSULTORIO8', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS09', N'CONSULTORIO9', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS10', N'CONSULTORIO10', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS11', N'CONSULTORIO11', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS12', N'CONSULTORIO12', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS13', N'CONSULTORIO13', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS14', N'CONSULTORIO14', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'CONS15', N'CONSULTORIO15', N'', N'', N'          ', 13)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP001', N'ADMINISIONISTA', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP002', N'MEDICA/O', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP003', N'ENFERMERA/O', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP004', N'LABORATORISTA', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP05', N'FARMACEUTICA/O', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP006', N'TECNICO', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP007', N'DELIVERY', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP008', N'ARCHIVERO', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP009', N'SEGURIDAD', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP010', N'SERVICIOS', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'EMP011', N'MED. TEMPORAL', N'', N'', N'          ', 14)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC01', N'PARTICULAR', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC02', N'ASEGURADO', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC03', N'CONVENIO', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC04', N'SOAT', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC05', N'EXTERNO', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'TPAC05', N'EXTERNO', N'', N'', N'          ', 15)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E001', N'ALERGIA E INMUNOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E002', N'CARDIOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E003', N'CIRUGIA ONCOLOGICA DE CABEZA Y CUELLO', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E004', N'CIRUGIA DE TORAX Y CARDIOVASCULAR', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E005', N'CIRUGIA GENERAL Y LAPAROSCOPICA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E006', N'CIRUGIA GENERAL Y ONCOLOGICA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E007', N'DERMATOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E008', N'RADIOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E009', N'ENDOCRINOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0010', N'ENFERMERIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0011', N'GASTROENTEROLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0012', N'GERIATRIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0013', N'GINECOLOGIA Y OBSTETRICIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0014', N'GINECOLOGIA ONCOLOGICA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0015', N'HEMATOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0016', N'MASTOLOGIA ', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0017', N'MEDICINA FISICA Y REHABILITACION', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0018', N'MEDICINA GENERAL', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0019', N'MEDICINA INTERNA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0020', N'NEFROLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0021', N'NEUMOLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0022', N'NEUROCIRUGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0023', N'NEUROLOGIA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0024', N'NUTRICION Y DIETETICA', N'', N'', N'          ', 16)
INSERT [dbo].[D00_TBDETALLE] ( [coddetTab], [descripcion], [abrev], [fuente], [estado], [idTab]) VALUES ( N'E0025', N'ODONTOLOGIA INTEGRAL', N'', N'', N'          ', 16)

INSERT [dbo].[D024_CAJA] ([nroCaja], [estado]) VALUES (1, N'activo')
GO
INSERT [dbo].[D024_CAJA] ([nroCaja], [estado]) VALUES (2, N'activo')
GO
INSERT [dbo].[D024_CAJA] ([nroCaja], [estado]) VALUES (3, N'activo')
GO
INSERT [dbo].[D024_CAJA] ([nroCaja], [estado]) VALUES (4, N'activo')
GO
INSERT [dbo].[D024_CAJA] ([nroCaja], [estado]) VALUES ( 5, N'activo')

insert into [dbo].[T109_ESTADOCITA](codEstadoCita,estado) values('001','RESERVADO')
insert into [dbo].[T109_ESTADOCITA](codEstadoCita,estado) values('002','ANULADO')
insert into [dbo].[T109_ESTADOCITA](codEstadoCita,estado) values('003','REPROGRAMADO')