// <auto-generated />
using System;
using HistClinica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HistClinica.Migrations
{
    [DbContext(typeof(ClinicaServiceContext))]
    [Migration("20200602220244_migraciontablas")]
    partial class migraciontablas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HistClinica.Models.CronoMedico", b =>
                {
                    b.Property<int>("idProgramMedica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsConsultorio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsEspecialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsEstado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsHrFin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsHrInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dsMedico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecProgramMedica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idConsultorio")
                        .HasColumnType("int");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("int");

                    b.Property<int>("idEstado")
                        .HasColumnType("int");

                    b.Property<int>("idMedico")
                        .HasColumnType("int");

                    b.Property<string>("mes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("semana")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProgramMedica");

                    b.ToTable("CronoMedico");
                });

            modelBuilder.Entity("HistClinica.Models.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codEspecialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codSigesa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codSubEspecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descSubEspecial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("HistClinica.Models.Medico", b =>
                {
                    b.Property<int>("idMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codMedico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecIngreso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("idEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("idEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nroColegio")
                        .HasColumnType("int");

                    b.Property<int?>("nroDni")
                        .HasColumnType("int");

                    b.Property<string>("nroRne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nroRuc")
                        .HasColumnType("int");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tpDocumento")
                        .HasColumnType("int");

                    b.HasKey("idMedico");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("HistClinica.Models.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apeMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apePaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("celular")
                        .HasColumnType("int");

                    b.Property<string>("centroEduca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicionRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dniAcom")
                        .HasColumnType("int");

                    b.Property<int>("dniPac")
                        .HasColumnType("int");

                    b.Property<string>("domiFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("edadAcom")
                        .HasColumnType("int");

                    b.Property<string>("estadoRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fonoFijo")
                        .HasColumnType("int");

                    b.Property<string>("fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAsegurado")
                        .HasColumnType("int");

                    b.Property<int>("idEstCivil")
                        .HasColumnType("int");

                    b.Property<int>("idEtnico")
                        .HasColumnType("int");

                    b.Property<int>("idFactorrh")
                        .HasColumnType("int");

                    b.Property<int>("idGrdInstruc")
                        .HasColumnType("int");

                    b.Property<int>("idOcupacion")
                        .HasColumnType("int");

                    b.Property<int>("idPacConvenio")
                        .HasColumnType("int");

                    b.Property<int>("idParentesco")
                        .HasColumnType("int");

                    b.Property<int>("idReligion")
                        .HasColumnType("int");

                    b.Property<int>("idSexo")
                        .HasColumnType("int");

                    b.Property<int>("idUbigeoNace")
                        .HasColumnType("int");

                    b.Property<int>("idUbigeoResi")
                        .HasColumnType("int");

                    b.Property<int>("idciaSeguro")
                        .HasColumnType("int");

                    b.Property<int>("iddatoReniec")
                        .HasColumnType("int");

                    b.Property<int>("iddatoSiteds")
                        .HasColumnType("int");

                    b.Property<int>("iddatoSunat")
                        .HasColumnType("int");

                    b.Property<int>("idemprConvenio")
                        .HasColumnType("int");

                    b.Property<int>("idgpoSangre")
                        .HasColumnType("int");

                    b.Property<int>("idtipoIafa")
                        .HasColumnType("int");

                    b.Property<int>("idtipoVia")
                        .HasColumnType("int");

                    b.Property<int>("idtpDocumento")
                        .HasColumnType("int");

                    b.Property<int>("idtpPaciente")
                        .HasColumnType("int");

                    b.Property<int>("interior")
                        .HasColumnType("int");

                    b.Property<int>("manzana")
                        .HasColumnType("int");

                    b.Property<string>("nombreAcom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroBlock")
                        .HasColumnType("int");

                    b.Property<int>("nroDpto")
                        .HasColumnType("int");

                    b.Property<int>("nroEtapa")
                        .HasColumnType("int");

                    b.Property<int>("nroKm")
                        .HasColumnType("int");

                    b.Property<int>("nroLote")
                        .HasColumnType("int");

                    b.Property<int>("nroRuc")
                        .HasColumnType("int");

                    b.Property<int>("nroVia")
                        .HasColumnType("int");

                    b.Property<int>("nrohc")
                        .HasColumnType("int");

                    b.Property<string>("razonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPaciente");

                    b.ToTable("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
