// <auto-generated />
using HistClinica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HistClinica.Migrations
{
    [DbContext(typeof(ClinicaServiceContext))]
    [Migration("20200531011720_initial migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HistClinica.Models.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apeMaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apePaterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("celular")
                        .HasColumnType("int");

                    b.Property<string>("centroEduca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condicionRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dniAcom")
                        .HasColumnType("int");

                    b.Property<int>("dniPac")
                        .HasColumnType("int");

                    b.Property<string>("domiFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("edadAcom")
                        .HasColumnType("int");

                    b.Property<string>("estadoRuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecNacimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fonoFijo")
                        .HasColumnType("int");

                    b.Property<string>("fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idAsegurado")
                        .HasColumnType("int");

                    b.Property<int>("idEstCivil")
                        .HasColumnType("int");

                    b.Property<int>("idEtnico")
                        .HasColumnType("int");

                    b.Property<int>("idFactorrh")
                        .HasColumnType("int");

                    b.Property<int>("idGrdInstruc")
                        .HasColumnType("int");

                    b.Property<int>("idOcupacion")
                        .HasColumnType("int");

                    b.Property<int>("idPacConvenio")
                        .HasColumnType("int");

                    b.Property<int>("idParentesco")
                        .HasColumnType("int");

                    b.Property<int>("idReligion")
                        .HasColumnType("int");

                    b.Property<int>("idSexo")
                        .HasColumnType("int");

                    b.Property<int>("idUbigeoNace")
                        .HasColumnType("int");

                    b.Property<int>("idUbigeoResi")
                        .HasColumnType("int");

                    b.Property<int>("idciaSeguro")
                        .HasColumnType("int");

                    b.Property<int>("iddatoReniec")
                        .HasColumnType("int");

                    b.Property<int>("iddatoSiteds")
                        .HasColumnType("int");

                    b.Property<int>("iddatoSunat")
                        .HasColumnType("int");

                    b.Property<int>("idemprConvenio")
                        .HasColumnType("int");

                    b.Property<int>("idgpoSangre")
                        .HasColumnType("int");

                    b.Property<int>("idtipoIafa")
                        .HasColumnType("int");

                    b.Property<int>("idtipoVia")
                        .HasColumnType("int");

                    b.Property<int>("idtpDocumento")
                        .HasColumnType("int");

                    b.Property<int>("idtpPaciente")
                        .HasColumnType("int");

                    b.Property<int>("interior")
                        .HasColumnType("int");

                    b.Property<int>("manzana")
                        .HasColumnType("int");

                    b.Property<string>("nombreAcom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreVia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nroBlock")
                        .HasColumnType("int");

                    b.Property<int>("nroDpto")
                        .HasColumnType("int");

                    b.Property<int>("nroEtapa")
                        .HasColumnType("int");

                    b.Property<int>("nroKm")
                        .HasColumnType("int");

                    b.Property<int>("nroLote")
                        .HasColumnType("int");

                    b.Property<int>("nroRuc")
                        .HasColumnType("int");

                    b.Property<int>("nroVia")
                        .HasColumnType("int");

                    b.Property<int>("nrohc")
                        .HasColumnType("int");

                    b.Property<string>("razonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idPaciente");

                    b.ToTable("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
